name: CD - Deploy to Server

on:
  workflow_run:
    workflows: ["CI - Build, Test, Docker Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'SSH OK'"

      - name: Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            docker pull brijraj12/hello:${{ github.event.workflow_run.head_commit.id }} &&
            docker stop springboot-app || true &&
            docker rm springboot-app || true &&
            docker run -d --name springboot-app -p 8080:8080 brijraj12/hello:${{ github.event.workflow_run.head_commit.id }}
          "
