name: CD - Deploy to Server
run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'SSH works!'"

# on:
#   workflow_run:
#     workflows: ["CI - Build, Test, Docker Push"]
#     types:
#       - completed

# jobs:
#   deploy:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up SSH key
#         run: |
#           mkdir -p ~/.ssh
#           # Decode the base64-encoded private key
#           echo "${{ secrets.SERVER_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy Docker Container
#         run: |
#           ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
#           # Pull Docker image tagged with this commit SHA
#           docker pull brijraj12/hello:${{ github.event.workflow_run.head_commit.id }} &&
          
#           # Stop and remove old container if it exists
#           docker stop springboot-app || true &&
#           docker rm springboot-app || true &&
          
#           # Run new container
#           docker run -d --name springboot-app -p 8080:8080 brijraj12/hello:${{ github.event.workflow_run.head_commit.id }}
#           "
