name: CD - Deploy Spring Boot on Linux Server (Docker Only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Stop existing container if running
        run: |
          docker stop hello || true
          docker rm hello || true

      - name: Pull latest image
        run: docker pull brijraj12/hello:latest
 
      - name: Run container
        run: |
          docker run -d \
            --name hello \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            --restart=always \
            brijraj12/hello:latest
